name: ${project.artifactId}

main: com.imaginarycode.minecraft.redisbungee.RedisBungee
version: ${project.version}
author: Chunkr and Govindas limework
authors:
  - chunkr
  - Govindas Limework
  - Coding-Area Team
# This is used so that we can automatically override default BungeeCord behavior.
softDepends: ["cmd_find", "cmd_list"]